In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
#Joining the both datasets

data=movies.merge(credits,on="title")
data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [7]:
#generes
#id
#keywords
#title
#overview
#cast
#crew

data=data[["id","title","overview","genres","keywords","cast","crew"]]

In [8]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
data.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
data.dropna(inplace=True)

In [11]:
data.duplicated().sum()

0

In [12]:
data.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
import ast

def transform(obj):
    
    temp=[]
    for i in ast.literal_eval(obj):
        temp.append(i['name'])
        
    return temp

data['genres'] = data["genres"].apply(transform)
data['keywords'] = data["keywords"].apply(transform)

In [14]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
import ast

def transform_cast(obj):
    counter = 0
    temp=[]
    for i in ast.literal_eval(obj):
        if counter != 3:
            temp.append(i['name'])
            counter = counter+1
            
        else:
            break
    return temp

data['cast'] = data["cast"].apply(transform_cast)

In [16]:
import json

def transform_cast(obj):
    temp=[]
    for i in json.loads(obj):
        if i["job"] == "Director":
            temp.append(i['name'])
            break
    return temp

data["crew"]=data["crew"].apply(transform_cast)

In [17]:
data.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [18]:
data["genres"]=data["genres"].apply(lambda x:[i.replace(" ","") for i in x])
data["cast"]=data["cast"].apply(lambda x:[i.replace(" ","") for i in x])
data["crew"]=data["crew"].apply(lambda x:[i.replace(" ","") for i in x])
data["kewwords"]=data["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
data['overview']=data['overview'].apply(lambda x:x.split())

In [19]:
data.head()

,id,title,overview,genres,keywords,cast,crew,kewwords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture clash, future, space war, space colon...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[based on novel, mars, medallion, space travel...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p..."

In [20]:
data['tags']=data['overview']+data['genres']+data["keywords"]+data['cast']+data['crew']

In [21]:
fdata=data[['id','title','tags']]

In [22]:
fdata['tags']=fdata['tags'].apply(lambda x:" ".join(x))
fdata['tags']=fdata['tags'].apply(lambda x: x.lower())

In [23]:
fdata.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [33]:
#Stemming
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [37]:
def stemming(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [39]:
fdata['tags']=fdata['tags'].apply(stemming)

In [44]:
fdata.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
cv = CountVectorizer(max_features=2500,stop_words='english')

In [47]:
vectors=cv.fit_transform(fdata['tags']).toarray()

In [48]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [52]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '1930',
 '1950',
 '1960',
 '1970',
 '1980',
 '19th',
 '20',
 '20th',
 '30',
 '3d',
 '40',
 '50',
 '60',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abil',
 'abl',
 'abov',
 'abus',
 'academi',
 'accept',
 'accid',
 'accident',
 'accompani',
 'account',
 'accus',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adamsandl',
 'adapt',
 'addict',
 'adolesc',
 'adopt',
 'adult',
 'adulteri',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'ag',
 'age',
 'agenc',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'air',
 'airplan',
 'airport',
 'al',
 'alaska',
 'albert',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alic',
 'alien',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allow',
 'alon',
 'alpacino',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'amanda',
 'amateur',
 'amaz',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'amnesia',
 'amp',
 'amus',
 'amyadam',
 'ancient',
 'anderson',
 'andi',
 'android',
 'angel',
 'angeles',
 'angelinajoli',
 'anger',
 'angri',
 'ani',
 'anim',
 'ann',
 'anna',
 'annehathaway',
 'anni',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'anthonyhopkin',
 'anti',
 'antoniobandera',
 'anyon',
 'anyth',
 'apart',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'apprentic',
 'approach',
 'archaeologist',
 'architect',
 'area',
 'arm',
 'armi',
 'army',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'art',
 'arthur',
 'artifici',
 'artist',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assum',
 'astronaut',
 'asylum',
 'athlet',
 'atom',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attorney',
 'attract',
 'audienc',
 'aunt',
 'australia',
 'australian',
 'author',
 'auto',
 'aveng',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bag',
 'balanc',
 'ball',
 'ballet',
 'band',
 'bank',
 'bar',
 'bare',
 'barn',
 'barri',
 'barrier',
 'base',
 'basebal',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'bed',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'behavior',
 'believ',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'benkingsley',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bet',
 'betray',
 'better',
 'beverli',
 'bibl',
 'big',
 'biggest',
 'biker',
 'billi',
 'billionair',
 'billybobthornton',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blame',
 'blind',
 'block',
 'blood',
 'bloodi',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'body',
 'bodyguard',
 'bomb',
 'bond',
 'book',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'bradpitt',
 'brain',
 'brave',
 'braveri',
 'break',
 'brendanfras',
 'brian',
 'bride',
 'bridg',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'broadcast',
 'broadway',
 'broken',
 'brooklyn',
 'brother',
 'brought',
 'brown',
 'bruce',
 'brucewilli',
 'brutal',
 'bu',
 'buddi',
 'build',
 'bullet',
 'bulli',
 'buri',
 'burn',
 'busi',
 'business',
 'businessman',
 'bust',
 'buy',
 'cabin',
 'california',
 'calvin',
 'came',
 'camera',
 'camerondiaz',
 'camp',
 'campaign',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'card',
 'care',
 'career',
 'carl',
 'carri',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'cathol',
 'caught',
 'caus',
 'cave',
 'celebr',
 'cell',
 'center',
 'central',
 'centuri',
 'century',
 'certain',
 'chain',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chang',
 'chao',
 'charact',
 'characters',
 'charg',
 'charl',
 'charli',
 'charlie',
 'charlizetheron',
 'charm',
 'chase',
 'cheat',
 'cheerlead',
 'chef',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'china',
 'chines',
 'choic',
 'choos',
 'chosen',
 'chri',
 'christ',
 'christian',
 'christianbal',
 'christma',
 'christopherplumm',
 'chronicl',
 'church',
 'cia',
 'cigarett',
 'cinema',
 'circu',
 'citi',
 'citizen',
 'city',
 'civil',
 'claim',
 'clair',
 'clan',
 'clash',
 'class',
 'classic',
 'classmat',
 'clean',
 'clear',
 'clerk',
 'client',
 'climb',
 'clinteastwood',
 'clock',
 'clone',
 'close',
 'closer',
 'club',
 'clue',
 'coach',
 'coast',
 'cocain',
 'code',
 'cold',
 'cole',
 'colinfarrel',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'command',
 'commerci',
 'commit',
 'common',
 'commun',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'complet',
 'complex',
 'complic',
 'comput',
 'concert',
 'condit',
 'confid',
 'conflict',
 'confront',
 'confus',
 'connect',
 'connor',
 'conquer',
 'consequences',
 'consid',
 'conspiraci',
 'construct',
 'consum',
 'contact',
 'contain',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'corpor',
 'corps',
 'corrupt',
 'cost',
 'costum',
 'count',
 'countri',
 'country',
 'countrysid',
 'coup',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 'cousin',
 'cover',
 'covert',
 'cowardli',
 'cowboy',
 'crack',
 'crash',
 'crazi',
 'creat',
 'creatur',
 'credit',
 'crew',
 'crime',
 'crimin',
 'criminals',
 'crisi',
 'crisis',
 'critic',
 'crocodil',
 'crook',
 'cross',
 'crush',
 'cuba',
 'cubagoodingjr',
 'cult',
 'cultur',
 'cure',
 'current',
 'curs',
 'custodi',
 'cut',
 'cyborg',
 'dad',
 'daili',
 'dan',
 'danaykroyd',
 'danc',
 'dancer',
 'danger',
 'daniel',
 'danni',
 'dannydevito',
 'dare',
 'dark',
 'date',
 'daughter',
 'dave',
 'david',
 'day',
 'dc',
 'dead',
 'deadli',
 'deal',
 'dealer',
 'dean',
 'death',
 'debt',
 'decad',
 'deceas',
 'deceit',
 'decept',
 'decid',
 'decis',
 'declar',
 'dedic',
 'deep',
 'defeat',
 'defend',
 'defens',
 'deliv',
 'demand',
 'demon',
 'dennisquaid',
 'denzelwashington',
 'depart',
 'depict',
 'depress',
 'descend',
 'desert',
 'design',
 'desir',
 'desper',
 'despit',
 'destin',
 'destroy',
 'destruct',
 'destruction',
 'detect',
 'detective',
 'determin',
 'detroit',
 'devast',
 'develop',
 'devic',
 'devil',
 'devot',
 'dialogu',
 'diamond',
 'dianekeaton',
 'dictat',
 'did',
 'die',
 'diego',
 'dies',
 'differ',
 'difficult',
 'dig',
 'diner',
 'dinner',
 'dinosaur',
 'direct',
 'director',
 'dirti',
 'disabl',
 'disappear',
 'disast',
 'discov',
 'discoveri',
 'diseas',
 'disfigur',
 'disguis',
 'disord',
 'distant',
 'district',
 'disturb',
 'dive',
 'divorc',
 'dna',
 'doctor',
 'document',
 'documentari',
 'doe',
 'doesn',
 'dog',
 'doll',
 'dollar',
 'dolphin',
 'domest',
 'domin',
 'don',
 'door',
 'doubl',
 'doubt',
 'dr',
 'drag',
 'dragon',
 'drama',
 'dramat',
 'draw',
 'drawn',
 'dream',
 'dreams',
 'dress',
 'drewbarrymor',
 'drink',
 'drive',
 'driven',
 'driver',
 'drop',
 'drug',
 'drugs',
 'drunk',
 'dual',
 'duel',
 'dump',
 'duo',
 'dure',
 'duringcreditssting',
 'dustinhoffman',
 'duti',
 'dwaynejohnson',
 'dynam',
 'dysfunct',
 'dystopia',
 'eager',
 'earli',
 'earn',
 'earth',
 'easi',
 'east',
 'eat',
 'eccentr',
 'econom',
 'eddi',
 'eddiemurphi',
 'edharri',
 'editor',
 'educ',
 'edward',
 'edwardnorton',
 'effect',
 'effort',
 'egg',
 'ego',
 'egypt',
 'el',
 'elderli',
 'elect',
 'electr',
 'elev',
 'elimin',
 'elit',
 'elizabeth',
 'elli',
 'els',
 'elv',
 'embark',
 'emerg',
 'emilyblunt',
 'emma',
 'emot',
 'emperor',
 'empir',
 'employ',
 'employe',
 'encount',
 'end',
 'enemi',
 'enemy',
 'energi',
 'enforc',
 'engag',
 'engin',
 'england',
 'english',
 'enjoy',
 'enlist',
 'ensembl',
 'enter',
 'enterpris',
 'entertain',
 'entir',
 'environment',
 'epic',
 'equal',
 'era',
 'erupt',
 'escap',
 'escape',
 'especi',
 'espionag',
 'establish',
 'estat',
 'estrang',
 'etern',
 'ethanhawk',
 'europ',
 'eve',
 'event',
 'events',
 'eventu',
 'everi',
 'everyday',
 'everyon',
 'everyth',
 'evid',
 'evil',
 'ewanmcgregor',
 'ex',
 'exact',
 'exactli',
 'examin',
 'exchang',
 'excit',
 'execut',
 'exist',
 'existence',
 'exorc',
 'exot',
 'expect',
 'expedit',
 'experi',
 'experienc',
 'experiment',
 'expert',
 'explod',
 'exploit',
 'explor',
 'explos',
 'expos',
 'extramarit',
 'extraordinari',
 'extraterrestri',
 'extrem',
 'eye',
 'face',
 'fact',
 'factori',
 'fail',
 'fairi',
 'faith',
 'fake',
 'fall',
 'fallen',
 'fals',
 'fame',
 'famili',
 'family',
 'famou',
 'fan',
 'fang',
 'fantasi',
 'fantast',
 'far',
 'farm',
 'farmer',
 'fascin',
 'fashion',
 'fast',
 'fat',
 'fatal',
 'fate',
 'father',
 'favorit',
 'fbi',
 'fear',
 'featur',
 'feder',
 'feel',
 'feet',
 'fellow',
 'femal',
 'festiv',
 'feud',
 'fiancé',
 'fiction',
 'field',
 'fierc',
 'fight',
 'fighter',
 'figur',
 'file',
 'film',
 'filmmak',
 'films',
 'final',
 'financi',
 'finish',
 'firm',
 'fish',
 'fisherman',
 'fistfight',
 'fit',
 'fix',
 'flashback',
 'flee',
 'fli',
 'flight',
 'flood',
 'florida',
 'flower',
 'focu',
 'focus',
 'folk',
 'follow',
 'food',
 'foot',
 'footag',
 'footbal',
 'forbidden',
 'forc',
 'force',
 'foreign',
 'forest',
 'forestwhitak',
 'forev',
 'forever',
 'forgiv',
 'form',
 'fortun',
 'foster',
 'fought',
 'fourth',
 'fox',
 'frame',
 'franc',
 'france',
 'francisco',
 'frank',
 'frankenstein',
 'fratern',
 'fraud',
 'freak',
 'fred',
 'freddi',
 'free',
 'freedom',
 'french',
 'fresh',
 'friend',
 'friends',
 'friendship',
 'frighten',
 'fu',
 'fugit',
 'fulfil',
 'fun',
 'fund',
 'funer',
 'futur',
 'future',
 'futurist',
 'ga',
 'gain',
 'galaxi',
 'gambl',
 'game',
 'gang',
 'gangster',
 'garag',
 'garden',
 'garyoldman',
 'gather',
 'gay',
 'genehackman',
 'gener',
 'genet',
 'geniu',
 'geoffreyrush',
 'georg',
 'georgeclooney',
 'gerardbutl',
 'german',
 'germani',
 'ghetto',
 'ghost',
 'giant',
 'gift',
 'girl',
 'girlfriend',
 'girls',
 'given',
 'glass',
 'global',
 'globe',
 'goal',
 'god',
 'goe',
 'gold',
 'golden',
 'golf',
 'gone',
 'good',
 'gordon',
 'gore',
 'gorgeou',
 'got',
 'gotham',
 'govern',
 'governor',
 'grace',
 'gradual',
 'graduat',
 'grand',
 'grandfath',
 'grant',
 'graphic',
 'grave',
 'great',
 'greatest',
 'greec',
 'greek',
 'green',
 'grief',
 'griev',
 'grip',
 'ground',
 'group',
 'grow',
 'grown',
 'gruesom',
 'guard',
 'guardian',
 'guest',
 'guid',
 'guilt',
 'gun',
 'gunfight',
 'gunsling',
 'guy',
 'gwynethpaltrow',
 'ha',
 'hacker',
 'hair',
 'half',
 ...]

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
sim=cosine_similarity(vectors)

In [86]:
sim.shape

(4806, 4806)

In [69]:
def reccomend(movie):
    index=fdata[fdata["title"] == movie].index[0]
    distances = sim[index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(fdata.iloc[i[0]].title)

In [79]:
reccomend("John Carter")

Riddick
Star Trek IV: The Voyage Home
Predators
The Hitchhiker's Guide to the Galaxy
Star Trek: Insurrection

In [83]:
import pickle

In [85]:
pickle.dump(fdata.to_dict(),open('movies.pkl','wb'))

In [87]:
pickle.dump(sim,open("sim.pkl",'wb'))

In [88]:
fdata

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...